server:
  port: 10010
spring:
  application:
    name: exam-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://exam-auth-server
          predicates:
            - Path=/auth/**     # /auth开头的请求都路由到exam-auth-server中
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9527"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - DELETE
              - POST
              - PUT
              - OPTIONS

eureka:
  instance:
    appname: exam-gateway
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/