server:
  port: 10010
spring:
  application:
    name: exam-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://exam-auth-server
          predicates:
            - Path=/auth/**     # /auth开头的请求都路由到exam-auth-server中
        - id: config
          uri: lb://exam-config-admin
          predicates:
            - Path=/xhr/**
        - id: config
          uri: lb://exam-user
          predicates:
            - Path=/user/**
        - id: question
          uri: lb://exam-questions
          predicates:
            - Path=/question/**
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    appname: exam-gateway
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/
exam:
  gateway:
    ignore-Paths:
      - /auth/auth/
# 发布时采用的地址为编排
---
spring:
  profiles: deploy
eureka:
  client:
    service-url:
      defaultZone: http://eureka:10011/eureka/