server:
 port: 10014
scca:
 rest:
   context-path: /xhr
spring:
 datasource:
   url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/exam_config
   driver-class-name: org.gjt.mm.mysql.Driver
   username: ${MYSQL_USERNAME:root}
   password: ${MYSQL_PASSWORD:123456}
   type: org.springframework.jdbc.datasource.DriverManagerDataSource
 jpa:
   hibernate:
     ddl-auto: update
 application:
   name: exam-config-admin
management:
  endpoints:
    web:
      exposure:
        include: "*"