server:
 port: 10014
scca:
 rest:
   context-path: /xhr
spring:
 datasource:
   url: jdbc:mysql://${localhost:MYSQL_HOST}:3306/exam_config
   driver-class-name: org.gjt.mm.mysql.Driver
   username: ${root:MYSQL_USERNAME}
   password: ${123456:MYSQL_PASSWORD}
   type: org.springframework.jdbc.datasource.DriverManagerDataSource
 jpa:
   hibernate:
     ddl-auto: update
 application:
   name: exam-config-admin
management:
  endpoints:
    web:
      exposure:
        include: "*"