server:
 port: 10014
scca:
 rest:
   context-path: /xhr
 ui:
   rest-server-context-path: /xhr
   rest-server-url: http://localhost:10014
spring:
 datasource:
   url: jdbc:mysql:///exam_config
   driver-class-name: org.gjt.mm.mysql.Driver
   username: root
   password: 123456
 jpa:
   hibernate:
     ddl-auto: update
 application:
   name: exam-config-admin