server:
  port: 10010
spring:
  application:
    name: exam-eureka
eureka:
  instance:
    hostname: localhost
    app-group-name: exam-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 开发阶段关闭保护模式
    eviction-interval-timer-in-ms: 5000 # client 清理时间