server:
  port: 10012
  servlet:
    context-path: /user
spring:
  application:
    name: exam-user
  datasource:
    url: jdbc:mysql:///exam_user
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect