server:
  port: 10015
spring:
  application:
    name: exam-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: exam-admin
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
scca:
  ui:
    rest-server-url: http://localhost:10014
    rest-server-context-path: /xhr