server:
  port: 10017
  servlet:
    context-path: /question
spring:
  datasource:
    password: 123456
    username: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///exam_questions
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  application:
    name: exam-questions
eureka:
  instance:
    appname: exam-questions
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.tlh.exam.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
# 发布时采用的地址为编排
---
spring:
  profiles: deploy
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}/exam_questions
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
eureka:
  client:
    service-url:
      defaultZone: http://eureka:10011/eureka/