server:
  port: 10015
spring:
  application:
    name: exam-monitor
  mail:
    host: smtp.qq.com
    username: 发送人qq邮箱
    password: qq邮箱的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: 收件人qq邮箱
          from: 发送人qq邮箱
eureka:
  instance:
    appname: exam-monitor
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS